newSheet()
fullScreen()newSheet()
DragToX("Order Date")
DragToY("Sales")
DragToColor("Category", -1)
showTrendLine()
newSheet()
DragToX("Sales")
DragToY("Profit")
DragToColor("Discount", -1)DragToColor("Profit", -1)